services:
  - type: web
    name: kesar-king-backend
    env: python
    plan: starter
    branch: main
    root: Backend
    buildCommand: pip install -r app/requirements.txt
    startCommand: uvicorn Backend.app.main:app --host 0.0.0.0 --port 10000 
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
